from app.routers import (
    weather,
    cities,
    departments,
    alerts,
    compare,
    history,
    rankings,
    export,
    favorites,
    invitations,
    auth,
    users_admin,
    roles_admin,
    audit_admin,
    admin_dashboard,
    data_file,
    climate_history
)

__all__ = [
    "weather",
    "cities",
    "departments",
    "alerts",
    "compare",
    "history",
    "rankings",
    "export",
    "favorites",
    "invitations",
    "auth",
    "users_admin",
    "roles_admin",
    "audit_admin",
    "admin_dashboard",
    "data_file",
    "climate_history"
]
